[2023-11-26T19:36:10.319+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task scheduled__2023-11-26T18:30:00+00:00 [queued]>
[2023-11-26T19:36:10.326+0100] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.first_task scheduled__2023-11-26T18:30:00+00:00 [queued]>
[2023-11-26T19:36:10.327+0100] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-26T19:36:10.341+0100] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): first_task> on 2023-11-26 18:30:00+00:00
[2023-11-26T19:36:10.343+0100] {standard_task_runner.py:57} INFO - Started process 12626 to run task
[2023-11-26T19:36:10.348+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'our_first_dag_v5', 'first_task', 'scheduled__2023-11-26T18:30:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/bash_test.py', '--cfg-path', '/tmp/tmporeznlks']
[2023-11-26T19:36:10.349+0100] {standard_task_runner.py:85} INFO - Job 3: Subtask first_task
[2023-11-26T19:36:10.394+0100] {task_command.py:416} INFO - Running <TaskInstance: our_first_dag_v5.first_task scheduled__2023-11-26T18:30:00+00:00 [running]> on host yzpt-Lenovo-ideapad-320S-14IKB
[2023-11-26T19:36:10.467+0100] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='first_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-26T18:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-26T18:30:00+00:00'
[2023-11-26T19:36:10.468+0100] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-26T19:36:10.469+0100] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\nPROJECT_ID=carburants-dataflow\nBUCKET_URL_INPUT_FILES=gs://$PROJECT_ID-input-files\nBUCKET_URL_TEMP=gs://$PROJECT_ID-temp\nDATASET_ID=carburants_dataset\nREGION=europe-west9\n\nSUFFIXE=light\n\n# GCS input file\nINPUT_FILE_PATTERN_URL=$BUCKET_URL_INPUT_FILES/instantane_$SUFFIXE.csv\nJSON_SCHEMA_FILE=$BUCKET_URL_INPUT_FILES/table_schema_df_$SUFFIXE.json\nUDF_PATH=$BUCKET_URL_INPUT_FILES/transform_csv_$SUFFIXE.js\n\n# BQ output table\nBQ_OUTPUT_TABLE=$PROJECT_ID:$DATASET_ID.$TABLE_ID\n\n# temporary directories\nTEMP_BQ_LOCATION=$BUCKET_URL_TEMP/temp_dir_bq\nTEMP_DF_LOCATION=$BUCKET_URL_TEMP/temp_dir_df\n\n# dataflow job with bigquery storage API support\ngcloud dataflow flex-template run api-carbu-data-$SUFFIXE    --template-file-gcs-location gs://dataflow-templates-europe-west9/latest/flex/GCS_Text_to_BigQuery_Flex     --region $REGION     --additional-experiments {}     --parameters inputFilePattern=$INPUT_FILE_PATTERN_URL,JSONPath=$JSON_SCHEMA_FILE,outputTable=$BQ_OUTPUT_TABLE,javascriptTextTransformGcsPath=$UDF_PATH,javascriptTextTransformFunctionName=process,bigQueryLoadingTemporaryDirectory=$TEMP_BQ_LOCATION,useStorageWriteApi=true,javascriptTextTransformReloadIntervalMinutes=0\n            ']
[2023-11-26T19:36:10.475+0100] {subprocess.py:86} INFO - Output:
[2023-11-26T19:36:11.411+0100] {subprocess.py:93} INFO - ERROR: (gcloud.dataflow.flex-template.run) INVALID_ARGUMENT: The template parameters are invalid. Details:
[2023-11-26T19:36:11.412+0100] {subprocess.py:93} INFO - outputTable: Parameter didn't match regex '.+:.+\..+'
[2023-11-26T19:36:11.412+0100] {subprocess.py:93} INFO - - '@type': type.googleapis.com/google.dataflow.v1beta3.InvalidTemplateParameters
[2023-11-26T19:36:11.412+0100] {subprocess.py:93} INFO -   parameterViolations:
[2023-11-26T19:36:11.413+0100] {subprocess.py:93} INFO -   - description: Parameter didn't match regex '.+:.+\..+'
[2023-11-26T19:36:11.413+0100] {subprocess.py:93} INFO -     parameter: outputTable
[2023-11-26T19:36:11.593+0100] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-26T19:36:11.602+0100] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yzpt/projects/dataflow_carburants/venv-airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-26T19:36:11.604+0100] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_first_dag_v5, task_id=first_task, execution_date=20231126T183000, start_date=20231126T183610, end_date=20231126T183611
[2023-11-26T19:36:11.623+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task first_task (Bash command failed. The command returned a non-zero exit code 1.; 12626)
[2023-11-26T19:36:11.642+0100] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-26T19:36:11.658+0100] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
